version: '3'
services:
  web:
    build: .
    ports:
      - 8080:9000
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: tribes
    ports:
      - 3307:3307
